title: 2018 Research Week Project
description: >
   October 29 - November 4, 2018.
   One week of research into new topics.
   7 days, seven little projects.
   Each day learning something new.
theme: jekyll-theme-midnight
show_downloads: false
