title: Lars' 2018 Research Week Project
description: >
   One week of research into new topics.
   7 days, seven little projects.
   Each day learning something new.
theme: jekyll-theme-midnight
show_downloads: false
